- type: ghostRole
  id: RedactedBorg
  name: ghost-role-information-redacted-borg
  description: ghost-role-information-redacted-borg-description
  rules: ghost-role-information-silicon-rules
  entityPrototype: PlayerBorgRedacted
  whitelisted: true

- type: ghostRole
  id: RemnantAICore
  name: ghost-role-information-redacted-core
  description: ghost-role-information-redacted-core-description
  rules: ghost-role-information-silicon-rules
  entityPrototype: StationAiBrainRedacted
  whitelisted: true

- type: ghostRole
  id: TSFMCAICore
  name: ghost-role-information-tsfmc-core
  description: ghost-role-information-tsfmc-core-description
  rules: ghost-role-information-silicon-rules
  entityPrototype: StationAiBrainTSFMC
  whitelisted: true

- type: ghostRole
  id: PDVAICore
  name: ghost-role-information-pdv-core
  description: ghost-role-information-pdv-description
  rules: ghost-role-information-silicon-rules
  entityPrototype: StationAiBrainPDV
  whitelisted: true
