- type: job
  id: PirateCaptain
  name: job-name-pirate-captain
  description: job-description-pirate-captain
  playTimeTracker: JobPirateCaptain
  requirements:
    - !type:OverallPlaytimeRequirement # mono start
      time: 108000 # 65 hours
    - !type:RoleTimeRequirement
      role: JobPirateFirstMate
      time: 3600 # 1 hour
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours # mono end
  whitelisted: true
  startingGear: PirateCaptainNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirateCaptain"
  supervisors: job-supervisors-nobody
  weight: 40
  displayWeight: 40
  setPreference: true
  guides: [ BasicLore, PhaethonDynasty ] # Mono
  access:
  - Pirate
  - RogueCommander
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - PirateNF
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateCaptainNFGear
  equipment:
    ears: ClothingHeadsetAltFreelancer
    #belt: ClothingBeltUtility # mono
    pocket1: BasePirateUplinkRadioPirateCaptain
    pocket2: EnergySword
  storage:
    back:
    - RadioHandheldNF # mono
    - ShipVoucherSaintie
