- type: department
  id: PMC
  name: department-PMC
  description: department-PMC-description
  color: "#7D8A3F"
  weight: 0 # accounted for in jobs
  roles:
  - Mercenary
  primary: false
  editorHidden: true

- type: department
  id: UnionOfSovietSocialistPlanets
  name: department-UnionOfSovietSocialistPlanets
  description: department-UnionOfSovietSocialistPlanets-description
  color: "#b2224b"
  weight: 117 # Master Chief!
  roles:
  - USSPCommissar
  - USSPSergeant
  - USSPCorporal
  - USSPMedic
  - USSPRifleman
  primary: false
  editorHidden: true
