- type: sectorService
  id: PirateBounties
  components:
  - type: SectorPirateBountyDatabase

- type: sectorService
  id: Mail
  components:
  - type: SectorLogisticStats
  - type: SectorMail # Contains sector-wide mail parameters

- type: sectorService
  id: ShuttleRecords
  components:
  - type: SectorShuttleRecords

# mono edit
- type: sectorService
  id: BankAccounts
  components:
  - type: SectorBank
    accounts:
      Frontier:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 14 # ~50K per hour, minimum wage employees!
      Nfsd:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 65 # ~234K per hour, about enough for minimum wage for the default TSFMC size
      Medical:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 18 # ~65K per hour, a bit over for the DOC MOM's wage.
      BlackMarket:
        !type:SectorBankAccountInfo
        balance: 8000
        increasePerSecond: 18 # ~65K per hour, they get ALOT just from people smuggling anyways.
# mono edit end

 # A global source of character records (DNA, fingerprints, criminal records, etc.)
- type: sectorService
  id: SectorRecords
  components:
  - type: StationRecords

- type: sectorService
  id: Alerts
  components:
  - type: AlertLevel
    alertLevelPrototype: stationAlerts

- type: sectorService
  id: BountyContracts
  components:
  - type: BountyContractData
