# Base prototypes can be found in \Resources\Prototypes\Recipes\Lathes\security.yml

# Recipes

- type: latheRecipe # crossbow bolt
  id: CrossbowBolt
  parent: BaseAmmoRecipe
  result: CrossbowBolt
  categories: # Mono
  - MiscAmmo
  - Ammo
  materials:
    Steel: 20

- type: latheRecipe # crossbow bolt
  id: CrossbowBoltBroadhead
  parent: BaseAmmoRecipe
  result: CrossbowBoltBroadhead
  categories: # Mono
  - MiscAmmo
  - Ammo
  materials:
    Steel: 25

- type: latheRecipe
  id: WeaponPistolPollock
  result: WeaponPistolPollock
  categories:
  - Weapons
  - Sidearms # Mono
  - Ballistic # Mono
  completetime: 3
  materials:
    Steel: 1000
    Plastic: 1200
    Plasteel: 1200

- type: latheRecipe
  id: ClothingEyesHudNfsd
  parent: ClothingEyesHudSecurity
  result: ClothingEyesHudNfsd

- type: latheRecipe
  id: HoloprojectorNfsd
  parent: ClothingEyesHudSecurity
  result: HoloprojectorNfsdEmpty
