- type: job
  id: USSPCommissar
  name: job-name-ussp-commissar
  description: job-description-ussp-commissar
  playTimeTracker: JobUSSPCommissar
  requirements:
  - !type:DepartmentTimeRequirement
    department: UnionOfSovietSocialistPlanets
    time: 72000 # 20 hours
  - !type:RoleTimeRequirement
    role: JobUSSPSergeant
    time: 10800 # 3 hrs
  - !type:RoleTimeRequirement
    role: JobUSSPMedic
    time: 10800 # 3 hrs
  - !type:OverallPlaytimeRequirement
    time: 144000 # 40 hrs
  startingGear: USSPCommissarGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconHeadOfSecurity" # TODO - new USSP icons
  supervisors: job-supervisors-ussp-highcomm
  canBeAntag: false
  guides: [ BasicLore, UnitedSovietSocialistPlanets ] # Mono
  weight: 40
  displayWeight: 40
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, UsspTrackingImplant ]
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - USSP
  - !type:AddLanguageSpecial
    languagesSpoken:
    - NovaCygniBasic
    languagesUnderstood:
    - NovaCygniBasic
  accessGroups:
  - GeneralAccess
  - USSPAA

- type: startingGear
  id: USSPCommissarGear
  equipment:
    pocket1: WeaponRevolverMatebaAP
    pocket2: SpeedLoader45_magnumAP
  storage:
    back:
    - RadioHandheldNF
