- type: job
  id: USSPCorporal
  name: job-name-ussp-corporal
  description: job-description-ussp-corporal
  playTimeTracker: JobUSSPCorporal
  requirements:
  - !type:DepartmentTimeRequirement
    department: UnionOfSovietSocialistPlanets
    time: 14400 # 4 hours
  - !type:OverallPlaytimeRequirement
    time: 14400 # 4 hrs
  startingGear: USSPCorporalGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconSecurityOfficer" # TODO - new USSP icons
  supervisors: job-supervisors-ussp-sergeant
  canBeAntag: false
  guides: [ BasicLore, UnitedSovietSocialistPlanets ] # Mono
  weight: 20
  displayWeight: 20
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, UsspTrackingImplant ]
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - USSP
  - !type:AddLanguageSpecial
    languagesSpoken:
    - NovaCygniBasic
    languagesUnderstood:
    - NovaCygniBasic
  accessGroups:
  - GeneralAccess
  - USSPLow

- type: startingGear
  id: USSPCorporalGear
  equipment:
    pocket1: WeaponPistolPollock
    pocket2: Magazine9x19mmPistolFMJ
  storage:
    back:
    - RadioHandheldNF
