- type: job
  id: USSPMedic
  name: job-name-ussp-medic
  description: job-description-ussp-medic
  playTimeTracker: JobUSSPMedic
  requirements:
  - !type:DepartmentTimeRequirement
    department: UnionOfSovietSocialistPlanets
    time: 14400 # 4 hours
  - !type:OverallPlaytimeRequirement
    time: 14400 # 4 hrs
  startingGear: USSPMedicGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconBrigmedic" # TODO - new USSP icons
  supervisors: job-supervisors-ussp-sergeant
  canBeAntag: false
  guides: [ BasicLore, UnitedSovietSocialistPlanets ] # Mono
  weight: 15
  displayWeight: 15
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, UsspTrackingImplant ]
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - USSP
  - !type:AddLanguageSpecial
    languagesSpoken:
    - NovaCygniBasic
    languagesUnderstood:
    - NovaCygniBasic
  accessGroups:
  - GeneralAccess
  - USSPLow

- type: startingGear
  id: USSPMedicGear
  equipment:
    pocket1: WeaponPistolPollock
    pocket2: Magazine9x19mmPistolFMJ
  storage:
    back:
    - MedkitCombatFilled
    - RadioHandheldNF
