- type: job
  id: USSPSergeant
  name: job-name-ussp-sergeant
  description: job-description-ussp-sergeant
  playTimeTracker: JobUSSPSergeant
  requirements:
  - !type:DepartmentTimeRequirement
    department: UnionOfSovietSocialistPlanets
    time: 54000 # 15 hours
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20 hrs
  startingGear: USSPSergeantGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconSeniorOfficer" # TODO - new USSP icons
  supervisors: job-supervisors-ussp-commissars
  canBeAntag: false
  guides: [ BasicLore, UnitedSovietSocialistPlanets ] # Mono
  weight: 30
  displayWeight: 30
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, UsspTrackingImplant ]
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - USSP
  - !type:AddLanguageSpecial
    languagesSpoken:
    - NovaCygniBasic
    languagesUnderstood:
    - NovaCygniBasic
  accessGroups:
  - GeneralAccess
  - USSPHigh

- type: startingGear
  id: USSPSergeantGear
  equipment:
    pocket1: WeaponPistolPollock
    pocket2: Magazine9x19mmPistolFMJ
  storage:
    back:
    - RadioHandheldNF
