# Mech Weapons
- type: latheRecipe
  id: WeaponMechCombatImmolationGun
  result: WeaponMechCombatImmolationGun
  completetime: 10
  materials:
    Steel: 2800
    Plastic: 1000
    Plasma: 750
    Glass: 500

- type: latheRecipe
  id: WeaponMechCombatSolarisLaser
  result: WeaponMechCombatSolarisLaser
  completetime: 10
  materials:
    Steel: 1650
    Plastic: 300
    Plasma: 250
    Glass: 200

- type: latheRecipe
  id: WeaponMechCombatFiredartLaser
  result: WeaponMechCombatFiredartLaser
  completetime: 10
  materials:
    Steel: 1200
    Plastic: 200
    Plasma: 150
    Glass: 50

- type: latheRecipe
  id: WeaponMechCombatUltraRifle
  result: WeaponMechCombatUltraRifle
  completetime: 10
  materials:
    Steel: 1000
    Plastic: 200

- type: latheRecipe
  id: WeaponMechCombatShotgun
  result: WeaponMechCombatShotgun
  completetime: 10
  materials:
    Steel: 1600
    Plastic: 550

- type: latheRecipe
  id: WeaponMechCombatShotgunIncendiary
  result: WeaponMechCombatShotgunIncendiary
  completetime: 10
  materials:
    Steel: 1500
    Plastic: 800
    Plasma: 300

- type: latheRecipe
  id: WeaponMechCombatDisabler
  result: WeaponMechCombatDisabler
  completetime: 10
  materials:
    Steel: 750
    Glass: 250
    Plastic: 300

- type: latheRecipe
  id: WeaponMechCombatFlashbangLauncher
  result: WeaponMechCombatFlashbangLauncher
  completetime: 10
  materials:
    Steel: 1200
    Glass: 300
    Plastic: 450

- type: latheRecipe
  id: WeaponMechCombatMissileRack8
  result: WeaponMechCombatMissileRack8
  completetime: 10
  materials:
    Steel: 2500
    Glass: 1500
    Plastic: 750

- type: latheRecipe
  id: MechEquipmentKineticAccelerator
  result: WeaponMechIndustrialKineticAccelerator
  completetime: 10
  materials:
    Steel: 1500
    Glass: 750
    Silver: 150

# Smartgun

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponSubMachineSmart
  result: WeaponSubMachineSmart
  categories: # Mono
  - SMGs
  - SmartGuns
  - Ballistic
  - Weapons
  materials:
    Steel: 1800
    Plastic: 750
    Silver: 500
    Gold: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineSmart
  result: MagazineSmart
  categories: # Mono
  - MiscAmmo
  - Ammo
  materials:
    Steel: 550
