- type: playTimeTracker
  id: JobNavyOfficer

- type: playTimeTracker
  id: JobNavyCaptain

- type: playTimeTracker
  id: JobNavyOfficerUndercover

- type: playTimeTracker
  id: JobSpecialOperationsOfficer

- type: playTimeTracker
  id: JobDiplomat

- type: playTimeTracker
  id: JobGovernmentMan