## Static recipes

- type: latheRecipePack
  id: SecurityEquipmentStatic
  recipes:
  - ClothingEyesHudSecurity
  - ForensicPad
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: SecurityPracticeStatic
  recipes:
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  # - WeaponFlareGunSecurity # Frontier

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: SecurityAmmoStatic
  recipes:
  - Wirecutter

- type: latheRecipePack
  id: SecurityWeaponsStatic
  recipes:
  - Flash
  - Stunbaton
  - CombatKnife
  - RiotShield

## Dynamic recipes

- type: latheRecipePack
  id: SecurityEquipment
  recipes:
  - ClothingBackpackElectropack
  - HoloprojectorSecurity
  - PortableRecharger
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - TelescopicShield

- type: latheRecipePack
  id: SecurityBoards
  abstract: true # Frontier: finally, spammable shuttle guns
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: SecurityExplosives
  recipes:
  - ExplosivePayload

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: SecurityAmmo
  recipes:
  - Wirecutter

- type: latheRecipePack
  id: SecurityWeapons
  recipes:
  - Truncheon
  - WeaponAdvancedLaser
  - WeaponLaserCannon
  - WeaponLaserCarbine
  - WeaponXrayCannon

- type: latheRecipePack
  id: SecurityDisablers
  recipes:
  - WeaponDisabler
  - WeaponDisablerSMG

# WD EDIT START
- type: latheRecipePack
  id: VisionGoggles
  recipes:
  - ClothingEyesNightVisionGoggles
  - ClothingEyesThermalVisionGoggles
# WD EDIT END
# Mono start
  - ClothingHelmetAttachmentNVGsBasic
  - ClothingHelmetAttachmentInfraredBasic
# Mono end
