- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic-nf
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hours - mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hours - mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 108000 # 30 hours - mono
  startingGear: BrigmedicGear
  icon: JobIconBrigmedicNF
  supervisors: job-supervisors-bailiff
  weight: 125
  displayWeight: 35
  canBeAntag: false
  guides: [ BasicLore, TransSolarFederation ] # Mono
  accessGroups:
  - GeneralNfsdBrigmedicAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
    - type: SurgerySpeedModifier
      SpeedModifier: 1.65
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: BrigmedicGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
    - EncryptionKeyMedical
    - Magazine45_ACPPistolFMJ
    - BaseSecurityUplinkRadioOfficer #Mono: Changed to officer uplink
    - RadioHandheldNF # Mono
