- type: job
  id: Cadet
  name: job-name-cadet-nf
  description: job-description-cadet-nf
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 32400 # 9 hours # mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours # mono
      inverted: true # Leave slots open for newer, less confident players.
  startingGear: CadetGear
  icon: JobIconCadetNF
  supervisors: job-supervisors-cadet
  weight: 70
  displayWeight: 10
  canBeAntag: false
  guides: [ BasicLore, TransSolarFederation ] # Mono
  setPreference: false # mono
  accessGroups:
  - CadetNfsdAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: CadetGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
    pocket2: BookSecurity
  storage:
    back:
    - Magazine45_ACPPistolFMJ
    - FederationMilitaryCredit50
    - BaseSecurityUplinkRadio
    - RadioHandheldNF # Mono
