- type: job
  id: PublicAffairsLiaison
  name: job-name-pal
  description: job-description-public-affairs-liaison
  playTimeTracker: JobPublicAffairsLiaison
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 28800 # 8 hours # mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hours # mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hours # mono
  startingGear: PublicAffairGear
  icon: "JobIconPublicAffairsLiaison"
  supervisors: job-supervisors-cadet
  canBeAntag: false
  guides: [ BasicLore, TransSolarFederation ] # Mono
  weight: 105
  displayWeight: 16
  setPreference: false # mono
  accessGroups:
  - CadetNfsdAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PublicAffairGear
  equipment:
    pocket1: HyperlinkBookSpaceLaw
    pocket2: BoxFolderClipboardPal
  storage:
    back:
    - Flash
    - BoxFolderPalBrown
    - BoxFolderNfsdForms
    - RubberStampPal
