- type: job
  id: Sheriff
  name: job-name-sheriff
  description: job-description-sheriff
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 144000 # 40 hours - mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 # 25 hours - mono
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 36000 # 10 hours - mono
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 270000 # 75 hours - mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 # 25 hours - mono
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 21600 # 6 hours - mono
  whitelisted: true
  startingGear: SheriffGear
  alwaysUseSpawner: true
  icon: JobIconSheriff
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 180
  displayWeight: 70
  canBeAntag: false
  guides: [ BasicLore, TransSolarFederation ] # Mono
  accessGroups:
  - AllAccess
  access: # Mono
  - TsfmcEngineering
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SheriffGear
  equipment:
    pocket1: WeaponEnergyGunMultiphase # DeltaV gun
    pocket2: EnergySwordNfsd
  storage:
    back:
    - Multitool
    - DoorRemoteNfsd
    - BaseSecurityUplinkRadioSheriff
    - ShipVoucherTsfmcColonel
